### ISSUE TITLE
Create a config file that allows enabling and disabling certain collectors in the cgroup tree

### ISSUE THREAD

**Issue by arianvp** [arianvp/cgroup-exporter#1]
enabling all collectors is quite a bit of data. Just on my desktop machine it's  10.000 individual metrics. Would
be cool if we can opt in and out of metrics in a config file. Thinking of something like this:

Note that collectors are inherited through the hierarchy.  Need to be disabled with `~<collector name>`

```yaml
collectors:  [memory.pressure]  # always collected memory.pressure for all cgroups
cgroup:
  system.slice:
    cgroup:
      systemd-journald.service:
        collectors: [io.pressure, io.stat]  # Want to know detailed IO stats for systemd-journald for whatever reason
      kubelet.service:
        collectors: [memory.events] # debug OOMs in kubelet.service
  kubepods.slice:
    collectors: [cpu.current, memory.current]
    cgroup:
      kubepods-burstable.slice:
        collectors: [~memory.pressure] # negated. We don't collect any metrics for burstable. dont care
      kubepods-besteffort.slice:
        collectors: [cpu.min, memory.min]
      kubepods-guaranteed.slice:
        collectors: [cpu.events, memory.events, cpu.min,  cpu.max, memory.min,]  # collect OOMs,  how often hitting memory.max, cpu.max etc
        
```
